# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('propellant', models.CharField(max_length=120)),
                ('isp_sl', models.IntegerField(blank=True, null=True)),
                ('isp_vacuum', models.IntegerField(blank=True, null=True)),
                ('thrust_sl', models.IntegerField(blank=True, null=True)),
                ('thrust_vacuum', models.IntegerField(blank=True, null=True)),
                ('chamber_pressure', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitMemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coolcats.Engine')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='launchplatform',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coolcats.Manufacturer'),
        ),
        migrations.AddField(
            model_name='engine',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coolcats.Manufacturer'),
        ),
    ]
