# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolcats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('propellant', models.CharField(max_length=120)),
                ('isp', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='launchplatform',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coolcats.Engine'),
        ),
    ]
