# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolcats', '0002_auto_20170910_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coolcats.Manufacturer'),
        ),
    ]
