# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolcats', '0003_engine_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='isp',
            new_name='isp_sl',
        ),
        migrations.AddField(
            model_name='engine',
            name='chamber_pressure',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='isp_vacuum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='thrust_sl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='thrust_vacuum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='launchplatform',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='launchplatform',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
