# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolcats', '0004_auto_20170911_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='chamber_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='isp_sl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='isp_vacuum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='thrust_sl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='thrust_vacuum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchplatform',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchplatform',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
