# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.5 on 2017-09-19 14:07
=======
# Generated by Django 1.11.5 on 2017-09-19 14:41
>>>>>>> 2aa5ff281c78aa78bd654482b8987c506f97e84a
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolcats', '0005_auto_20170911_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitMemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
