# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=120)),
                ('spectator_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='consert',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Stage'),
        ),
    ]
