# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('concert_start_time', models.TimeField(blank=True, null=True)),
                ('concert_end_time', models.TimeField(blank=True, null=True)),
                ('tickets', models.IntegerField(blank=True, null=True)),
                ('number_of_tech', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('tickets', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Festival'),
        ),
        migrations.AddField(
            model_name='concert',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Stage'),
        ),
    ]
