# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='derpfield',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
