# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_bookingoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
