# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_concert_derpfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='derpfield',
        ),
    ]
