# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20170919_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
