# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_artist_artist_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='tech_needs',
        ),
        migrations.AddField(
            model_name='bookingoffer',
            name='tech_needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
