# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_concert_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='spectator_amount',
        ),
        migrations.AddField(
            model_name='concert',
            name='number_of_tech',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
