# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20170926_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='technicians',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
