# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20170928_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoffer',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
