# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0005_auto_20170928_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingoffer',
            name='artist_id',
        ),
        migrations.AddField(
            model_name='bookingoffer',
            name='artist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Artist'),
        ),
        migrations.AddField(
            model_name='bookingoffer',
            name='artist_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
