# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_festival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='concert',
        ),
    ]
