# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20170928_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ('concert_start_time', 'name')},
        ),
    ]
