# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20170928_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='time_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.TimeSlot'),
        ),
        migrations.AddField(
            model_name='stage',
            name='time_slots',
            field=models.ManyToManyField(blank=True, null=True, to='booking.TimeSlot'),
        ),
    ]
