# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20170928_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='time_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='time_slots',
            field=models.ManyToManyField(blank=True, to='booking.TimeSlot'),
        ),
    ]
