# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_festival_concerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='concerts',
            field=models.ManyToManyField(to='booking.Concert', verbose_name='list of concerts'),
        ),
    ]
