# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20170928_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='stage_id',
            new_name='stage',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='concert_end_time',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='concert_start_time',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Stage'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='accepted_by_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='approved_by_bm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='tech_needs',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='sold_tickets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='audience_cap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
