# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20171003_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='concert_id',
            new_name='concert',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='festival_id',
            new_name='festival',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='festival_id',
            new_name='festival',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='festival_id',
            new_name='festival',
        ),
    ]
