# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_festival_concerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='concerts',
        ),
        migrations.AddField(
            model_name='concert',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Festival'),
        ),
        migrations.AddField(
            model_name='festival',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
