# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20170925_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('genre', models.CharField(max_length=120)),
                ('tech_needs', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='concert',
            name='artist',
        ),
        migrations.AddField(
            model_name='artist',
            name='concert_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Concert'),
        ),
        migrations.AddField(
            model_name='artist',
            name='festival_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Festival'),
        ),
    ]
