# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0011_auto_20170925_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='technicians_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
