# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_concert_technicians_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='technicians_id',
            new_name='technicians',
        ),
    ]
