# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20171003_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='stage_id',
            new_name='stage',
        ),
    ]
