# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20171003_1434'),
        ('booking', '0015_bookingoffer_offering_time'),
    ]

    operations = [
    ]
