# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0019_auto_20171003_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoffer',
            name='artist_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='booker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booker', to=settings.AUTH_USER_MODEL),
        ),
    ]
