# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20171003_1653'),
        ('booking', '0016_auto_20171003_1721'),
    ]

    operations = [
    ]
