# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_merge_20171003_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ('time_slot__start_date', 'name')},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='concert',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Stage'),
        ),
    ]
