# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20171005_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='festival',
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
