# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_auto_20171007_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='concert',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='festival',
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
