# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_auto_20171007_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingoffer',
            name='artist_manager',
        ),
    ]
