# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_remove_bookingoffer_artist_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoffer',
            name='offering_time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
