# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_remove_concert_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
