# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_auto_20171007_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.Artist'),
            preserve_default=False,
        ),
    ]
