# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20171008_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoffer',
            name='booker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booker', to=settings.AUTH_USER_MODEL),
        ),
    ]
