# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
    ]
