# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 20:44
from __future__ import unicode_literals

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_auto_20171008_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='audience_cap',
            field=models.IntegerField(null=True, validators=[booking.validators.validate_even]),
        ),
    ]
