# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_auto_20171008_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingoffer',
            name='offering_time',
        ),
    ]
