# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_remove_bookingoffer_offering_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoffer',
            name='offering_time',
            field=models.DateTimeField(null=True),
        ),
    ]
