# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_bookingoffer_offering_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoffer',
            name='artist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Artist'),
        ),
    ]
