# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 21:33
from __future__ import unicode_literals

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_auto_20171008_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoffer',
            name='offering_time',
            field=models.DateField(null=True, validators=[booking.validators.validate_future]),
        ),
    ]
