# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_auto_20171008_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingoffer',
            old_name='offering_time',
            new_name='offering_date',
        ),
    ]
