# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 21:35
from __future__ import unicode_literals

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_auto_20171008_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='start_date',
            field=models.DateField(blank=True, null=True, validators=[booking.validators.validate_future]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_date',
            field=models.DateField(null=True, validators=[booking.validators.validate_future]),
        ),
    ]
