# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_auto_20171008_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='audience_cap',
            field=models.IntegerField(null=True),
        ),
    ]
