# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_auto_20171009_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.Festival'),
        ),
    ]
