# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_auto_20171009_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ('time_slot__start_date', 'artist')},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='name',
        ),
    ]
