# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0055_auto_20171009_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingoffer',
            name='name',
        ),
    ]
