# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0056_remove_bookingoffer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ('start_date', 'start_time', 'stage')},
        ),
        migrations.AddField(
            model_name='bookingoffer',
            name='artist_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
