# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0058_auto_20171009_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoffer',
            name='artist_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
