# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0060_auto_20171009_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingoffer',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookingoffer',
            name='offering_date',
        ),
        migrations.RemoveField(
            model_name='bookingoffer',
            name='offering_stage',
        ),
    ]
