# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0062_bookingoffer_offering_time_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingoffer',
            options={'ordering': ('offering_time_slot', 'offering_time_slot__stage')},
        ),
    ]
