# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_auto_20171010_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('artist_rev', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='booking.Review'),
        ),
    ]
