# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0065_auto_20171024_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
