# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0066_auto_20171031_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='tech_meat',
        ),
        migrations.AddField(
            model_name='concert',
            name='techs_meat',
            field=models.ManyToManyField(blank=True, related_name='techs_meat', to=settings.AUTH_USER_MODEL),
        ),
    ]
