# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0068_auto_20171031_1616'),
        ('booking', '0065_concert_costs'),
    ]

    operations = [
    ]
