# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0069_merge_20171102_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='contact_person',
            field=models.ManyToManyField(blank=True, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
