# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0069_merge_20171031_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='contact_info',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
