# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0069_merge_20171031_1637'),
        ('booking', '0065_artist_artist_rev'),
    ]

    operations = [
    ]
