# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0069_merge_20171102_0949'),
        ('booking', '0070_artist_contact_info'),
        ('booking', '0070_merge_20171031_1924'),
    ]

    operations = [
    ]
