# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0070_concert_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='artist_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artist_man', to=settings.AUTH_USER_MODEL),
        ),
    ]
