# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0072_merge_20171105_1848'),
        ('booking', '0072_merge_20171107_1413'),
    ]

    operations = [
    ]
