# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0073_auto_20171107_1615'),
        ('booking', '0073_auto_20171107_1631'),
    ]

    operations = [
    ]
